# Generated by Django 6.0.2 on 2026-02-15 16:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CookieConsentConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="Cookie Settings", max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        default="We use cookies to improve your experience on our website. Some cookies are essential for the website to function, while others help us understand how you use our site.",
                        help_text="Main text displayed in the cookie banner",
                        verbose_name="Description",
                    ),
                ),
                (
                    "privacy_policy_url",
                    models.URLField(
                        blank=True, help_text="Link to privacy policy page", verbose_name="Privacy Policy URL"
                    ),
                ),
                (
                    "imprint_url",
                    models.URLField(
                        blank=True, help_text="Link to imprint/legal notice page", verbose_name="Imprint URL"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[("bottom", "Bottom Bar"), ("top", "Top Bar"), ("center", "Center Modal")],
                        default="bottom",
                        max_length=20,
                        verbose_name="Position",
                    ),
                ),
                (
                    "accept_all_label",
                    models.CharField(default="Accept All", max_length=50, verbose_name="Accept All Button Label"),
                ),
                (
                    "reject_all_label",
                    models.CharField(default="Only Essential", max_length=50, verbose_name="Reject Button Label"),
                ),
                (
                    "settings_label",
                    models.CharField(default="Settings", max_length=50, verbose_name="Settings Button Label"),
                ),
                (
                    "save_label",
                    models.CharField(default="Save Preferences", max_length=50, verbose_name="Save Button Label"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Cookie Consent Configuration",
                "verbose_name_plural": "Cookie Consent Configurations",
            },
        ),
        migrations.CreateModel(
            name="ConsentVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=20, verbose_name="Version")),
                (
                    "change_description",
                    models.TextField(help_text="What changed in this version", verbose_name="Change Description"),
                ),
                (
                    "requires_reconsent",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, all users must re-consent",
                        verbose_name="Requires Re-consent",
                    ),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True, verbose_name="Published At")),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Complete snapshot of config and cookie groups at time of publishing",
                        verbose_name="Snapshot",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="djangocms_cookie_love.cookieconsentconfig",
                        verbose_name="Configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Version",
                "verbose_name_plural": "Consent Versions",
                "ordering": ["-published_at"],
                "unique_together": {("config", "version")},
            },
        ),
        migrations.CreateModel(
            name="CookieGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(
                        help_text="Explains to the user what this cookie group does", verbose_name="Description"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Required groups cannot be deactivated (e.g. Essential)",
                        verbose_name="Required",
                    ),
                ),
                (
                    "is_default_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Pre-selected state (only allowed for required groups per GDPR)",
                        verbose_name="Enabled by Default",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "cookies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of cookies: [{"name": "...", "provider": "...", "duration": "...", "purpose": "..."}]',
                        verbose_name="Cookies",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cookie_groups",
                        to="djangocms_cookie_love.cookieconsentconfig",
                        verbose_name="Configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cookie Group",
                "verbose_name_plural": "Cookie Groups",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "consent_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Consent ID"),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the user's IP address", max_length=64, verbose_name="IP Hash"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "consent_method",
                    models.CharField(
                        choices=[
                            ("banner_accept_all", "Banner – Accept All"),
                            ("banner_reject", "Banner – Reject Optional"),
                            ("settings", "Settings Modal"),
                            ("api", "API"),
                        ],
                        max_length=30,
                        verbose_name="Consent Method",
                    ),
                ),
                ("consent_given_at", models.DateTimeField(auto_now_add=True, verbose_name="Consent Given At")),
                (
                    "accepted_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="consents",
                        to="djangocms_cookie_love.cookiegroup",
                        verbose_name="Accepted Groups",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_consents",
                        to="djangocms_cookie_love.consentversion",
                        verbose_name="Consent Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Consent",
                "verbose_name_plural": "User Consents",
                "ordering": ["-consent_given_at"],
            },
        ),
    ]
