# Generated by Django 6.0.2 on 2026-02-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_cookie_love", "0002_default_cookie_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userconsent",
            name="consent_method",
            field=models.CharField(
                choices=[
                    ("banner_accept_all", "Banner – Accept All"),
                    ("banner_reject", "Banner – Reject Optional"),
                    ("settings", "Settings Modal"),
                    ("revoke", "Revoke"),
                    ("api", "API"),
                ],
                max_length=30,
                verbose_name="Consent Method",
            ),
        ),
    ]
