# Generated by Django 6.0.2 on 2026-02-18 18:25

import cms.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        ("djangocms_cookie_love", "0004_cookie_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookieconsentconfig",
            name="imprint_page",
            field=cms.models.fields.PageField(
                blank=True,
                help_text="Select an internal CMS page for the imprint",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cookie_config_imprint_configs",
                to="cms.page",
                verbose_name="Imprint Page",
            ),
        ),
        migrations.AddField(
            model_name="cookieconsentconfig",
            name="privacy_policy_page",
            field=cms.models.fields.PageField(
                blank=True,
                help_text="Select an internal CMS page for the privacy policy",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cookie_config_privacy_configs",
                to="cms.page",
                verbose_name="Privacy Policy Page",
            ),
        ),
        migrations.AlterField(
            model_name="cookieconsentconfig",
            name="imprint_url",
            field=models.URLField(
                blank=True,
                help_text="External URL – only used if no internal page is selected",
                verbose_name="Imprint URL (external)",
            ),
        ),
        migrations.AlterField(
            model_name="cookieconsentconfig",
            name="privacy_policy_url",
            field=models.URLField(
                blank=True,
                help_text="External URL – only used if no internal page is selected",
                verbose_name="Privacy Policy URL (external)",
            ),
        ),
    ]
